import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import{flushSync}from'react-dom';
import '@fontsource/bebas-neue/latin-400.css';
import '@fontsource/dm-serif-display/latin-400.css';
import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/dm-sans/latin-500.css';
import '@fontsource/dm-sans/latin-700.css';
import '@fontsource/dm-sans/latin-800.css';
import{DEFAULT,PRESETS,MAX_TEXT,encodeState,decodeState,validateState}from'./state.mjs';
import{paint,waitFonts,families,type Poster}from'./render';
import './style.css';
function Icon({name,...rest}:{name:string;[k:string]:unknown}){const p:Record<string,React.ReactNode>={shuffle:<><path d="m4 5 4 0 8 14h4M17 16l3 3-3 3M4 19h4l3-5M14 9l2-4h4M17 2l3 3-3 3"/></>,share:<><path d="M12 16V3m-4 4 4-4 4 4M5 13v7h14v-7"/></>,download:<><path d="M12 3v12m-4-4 4 4 4-4M5 17v4h14v-4"/></>,expand:<><path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/></>,check:<path d="m5 12 4 4L19 6"/>,close:<path d="m6 6 12 12M6 18 18 6"/>,left:<><path d="M4 5h16M4 10h10M4 15h16M4 20h10"/></>,center:<><path d="M4 5h16M7 10h10M4 15h16M7 20h10"/></>,right:<><path d="M4 5h16M10 10h10M4 15h16M10 20h10"/></>,edit:<><path d="m4 16 12-12 4 4L8 20H4v-4ZM14 6l4 4"/></>};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...rest}>{p[name]||p.check}</svg>}
function PosterCanvas({state,className='',onError}:{state:Poster;className?:string;onError?:(message:string)=>void}){
 const ref=useRef<HTMLCanvasElement>(null);
 useLayoutEffect(()=>{const canvas=ref.current!;let active=true;
 const render=()=>{if(!active)return;const box=canvas.getBoundingClientRect();if(box.width&&box.height)paint(canvas,state,Math.round(box.width*Math.min(devicePixelRatio,2)),Math.round(box.height*Math.min(devicePixelRatio,2)));};
 render();waitFonts(state).then(render).catch(()=>onError?.('No se pudo cargar la tipografía. Prueba a recargar.'));
 const observer=new ResizeObserver(render);observer.observe(canvas);return()=>{active=false;observer.disconnect();};
 },[state]);
 return <canvas ref={ref} className={className} role="img" aria-label={state.text}>{state.text}</canvas>;
}
function initial(){try{return location.hash ? {state:decodeState(location.hash.replace('#edit:','#')),view:!location.hash.startsWith('#edit:'),error:''}:{state:DEFAULT,view:false,error:''};}catch(e){return {state:DEFAULT,view:false,error:(e as Error).message};}}
const boot=initial();
function App(){
 const[state,setState]=useState<Poster>(boot.state),[view,setView]=useState(boot.view),[error,setError]=useState(boot.error),[toast,setToast]=useState(''),[shareOpen,setShareOpen]=useState(false),[shareUrl,setShareUrl]=useState(''),[busy,setBusy]=useState(false),[ratio,setRatio]=useState('landscape');
 const stateRef=useRef(state);stateRef.current=state;
 const dialog=useRef<HTMLDialogElement>(null),shareInput=useRef<HTMLInputElement>(null),toastTimer=useRef<ReturnType<typeof setTimeout>>(undefined),stage=useRef<HTMLDivElement>(null);
 function notify(s:string){setToast(s);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),3000);}
 function patch(p:Partial<Poster>){setState(prev=>({...prev,...p}));}
 function getUrl(){return location.href.split('#')[0]+encodeState(state);}
 useEffect(()=>{const onHash=()=>{try{if(location.hash){setState(decodeState(location.hash.replace('#edit:','#')));setView(!location.hash.startsWith('#edit:'));}else setView(false);setError('');}catch(e){setError((e as Error).message);setView(false);}};addEventListener('hashchange',onHash);return()=>removeEventListener('hashchange',onHash);},[]);
 useEffect(()=>{if(shareOpen)dialog.current?.showModal();else dialog.current?.close();},[shareOpen]);
 useEffect(()=>{const esc=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!dialog.current?.open)setView(false);};addEventListener('keydown',esc);return()=>removeEventListener('keydown',esc);},[]);
 useEffect(()=>{
  const ctx=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>|void}}).modelContext;if(!ctx)return;
  const life=new AbortController();try{Promise.resolve(ctx.registerTool({name:'configure_gzaas_message',description:'Set the message text in the visible Gzaas editor. Does not publish or share.',inputSchema:{type:'object',properties:{text:{type:'string',minLength:1,maxLength:280}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{const text=(input as {text?:unknown})?.text;if(typeof text!=='string')throw Error('text must be a string');const next=validateState({...stateRef.current,text});flushSync(()=>{setState(next);setView(false);});return{configured:true,text:next.text};}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();
 },[]);
 useEffect(()=>{if(view||error)return;const timer=setTimeout(()=>{try{history.replaceState(null,'',location.pathname+location.search+encodeState(state).replace('#','#edit:'));}catch{}},200);return()=>clearTimeout(timer);},[state,view,error]);
 const invalid=!state.text.trim()||[...state.text].length>MAX_TEXT||state.text.split('\n').length>12;
 async function share(){try{const url=getUrl();setShareUrl(url);setShareOpen(true);}catch(e){setError((e as Error).message);}}
 async function copy(){try{await navigator.clipboard.writeText(shareUrl);notify('Enlace copiado. ¡A compartir!');}catch{shareInput.current?.focus();shareInput.current?.select();notify('Selecciona y copia el enlace.');}}
 async function nativeShare(){try{await navigator.share({title:'Un mensaje para ti — gzaas!',url:shareUrl});}catch(e){if((e as Error).name!=='AbortError')notify('No se pudo abrir el menú. Puedes copiar el enlace.');}}
 async function download(){setBusy(true);try{await waitFonts(state);const canvas=document.createElement('canvas');const [w,h]=ratio==='square'?[1600,1600]:ratio==='portrait'?[1200,1600]:[1920,1440];paint(canvas,state,w,h);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('No se pudo crear la imagen.')),'image/png'));const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='gzaas.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Tu imagen está lista.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function surprise(){const current=PRESETS.findIndex(p=>p.bg===state.bg);let idx;do{idx=Math.floor(Math.random()*PRESETS.length);}while(idx===current);const{name,sample,...style}=PRESETS[idx];patch(style);notify(name);}
 async function fullScreen(){setView(true);}
 function edit(){setView(false);if(document.fullscreenElement)void document.exitFullscreen();}
 return <div className={view?'app viewer':'app'}>
 {!view&&<><header className="topbar"><a className="logo" href={location.pathname} aria-label="Gzaas, inicio">gzaas<span>!</span></a><span className="edition">MENSAJES CON PERSONALIDAD</span><a className="origin" href="https://github.com/ojoven/gzaas" target="_blank" rel="noreferrer">La idea original <span>↗</span></a></header>
 <main><div className="intro"><div><span className="eyebrow">POCAS PALABRAS. MUCHA ACTITUD.</span><h1>Dilo a lo grande<span>.</span></h1></div><button className="button secondary shuffle" onClick={surprise}><Icon name="shuffle"/>Sorpréndeme</button></div>
 {error&&<div role="alert" className="error"><span>{error}</span><button onClick={()=>{setError('');history.replaceState(null,'',location.pathname+location.search);}} aria-label="Cerrar aviso"><Icon name="close"/></button></div>}
 <div className="workspace"><section className="preview-column" aria-label="Vista previa del mensaje"><div className="preview-heading"><span>EL MENSAJE</span><div className="ratio-controls" aria-label="Proporción del cartel">{[['landscape','4:3'],['square','1:1'],['portrait','3:4']].map(([key,label])=><button key={key} className={ratio===key?'selected':''} onClick={()=>setRatio(key)} aria-pressed={ratio===key}>{label}</button>)}</div></div><div className={'preview-bed '+ratio}><div className={'poster-frame '+ratio} ref={stage}><PosterCanvas state={state} onError={setError}/></div></div><div className="preview-bottom"><span>Un mensaje. Toda la pantalla.</span><button className="text-button" disabled={invalid} onClick={fullScreen}><Icon name="expand"/>Ver en grande</button></div></section>
 <aside className="editor"><div className="field-label"><label htmlFor="message">Tu mensaje</label><span>{[...state.text].length}/{MAX_TEXT}</span></div><textarea id="message" value={state.text} placeholder="Eso que quieres decir…" onChange={e=>patch({text:[...e.target.value].slice(0,MAX_TEXT).join('')})} spellCheck={false}/>{state.text.split('\n').length>12&&<p className="field-error">Usa como máximo 12 líneas.</p>}
 <div className="field-label"><label htmlFor="font">Tipografía</label></div><select id="font" value={state.font} onChange={e=>patch({font:e.target.value})}><option value="bebas">Bebas Neue · Contundente</option><option value="serif">DM Serif · Con carácter</option><option value="sans">DM Sans · Sin rodeos</option></select>
 <div className="colors"><label><span>Texto</span><div className="color-input"><input type="color" aria-label="Color del texto" value={state.fg} onChange={e=>patch({fg:e.target.value})}/><span>{state.fg.toUpperCase()}</span></div></label><label><span>Fondo</span><div className="color-input"><input type="color" aria-label="Color del fondo" value={state.bg} onChange={e=>patch({bg:e.target.value})}/><span>{state.bg.toUpperCase()}</span></div></label></div>
 <div className="field-label"><label htmlFor="size">Intensidad</label><span>{state.size}%</span></div><input id="size" type="range" min="40" max="100" value={state.size} onChange={e=>patch({size:+e.target.value})}/>
 <div className="format-row"><div className="align-buttons" aria-label="Alineación">{['left','center','right'].map((a,i)=><button key={a} aria-label={['Alinear a la izquierda','Centrar','Alinear a la derecha'][i]} aria-pressed={state.align===a} onClick={()=>patch({align:a})} className={state.align===a?'selected':''}><Icon name={a}/></button>)}</div><select aria-label="Efecto del texto" value={state.effect} onChange={e=>patch({effect:e.target.value})}><option value="none">Sin efecto</option><option value="shadow">Sombra</option><option value="outline">Contorno</option></select></div>
 <div className="field-label"><span>Textura</span></div><div id="pattern" className="segmented" role="group" aria-label="Textura del fondo">{[['none','Lisa'],['dots','Puntos'],['grid','Cuadrícula'],['lines','Líneas']].map(([p,label])=><button key={p} aria-pressed={state.pattern===p} className={state.pattern===p?'selected':''} onClick={()=>patch({pattern:p})}>{label}</button>)}</div>
 <div className="field-label"><label htmlFor="animation">Al abrir el mensaje</label></div><select id="animation" value={state.animation} onChange={e=>patch({animation:e.target.value})}><option value="none">Sin animación</option><option value="reveal">Aparecer suavemente</option><option value="float">Flotar</option></select>
 <div className="editor-actions"><button className="button primary" onClick={share} disabled={invalid}><Icon name="share"/>Compartir mensaje</button><button className="button secondary" disabled={invalid||busy} onClick={download}><Icon name="download"/>{busy?'Preparando…':'Descargar imagen'}</button></div></aside></div>
 <section className="styles-section" aria-label="Estilos de mensaje"><div className="section-title"><h2>¿Qué quieres transmitir?</h2><span>Elige un estilo. Hazlo tuyo.</span></div><div className="styles">{PRESETS.map((p,i)=>{const active=['font','fg','bg','pattern','effect'].every(k=>state[k as keyof Poster]===p[k as keyof typeof p]);return <button key={p.name} className={'style-card '+(active?'active':'')} onClick={()=>{const{name,sample,...style}=p;patch(style);}} aria-pressed={active}><div className="swatch" style={{background:p.bg,color:p.fg,fontFamily:families[p.font],fontWeight:p.font==='sans'?800:400}}>{p.sample.split('\n').map((l,j)=><span key={j}>{l}</span>)}{active&&<span className="active-mark"><Icon name="check"/></span>}</div><div className="style-name"><span>{p.name}</span><small>0{i+1}</small></div></button>})}</div></section>
 <footer><span className="footer-logo">gzaas!</span><span>Las palabras son tuyas. El estilo también.</span><a href="https://github.com/ojoven/gzaas" target="_blank" rel="noreferrer">Inspirado en el Gzaas! de ojoven</a></footer></main></>}
 {view&&<><div className={'viewer-poster motion-'+state.animation}><PosterCanvas state={state}/></div><div className="viewer-bar"><span className="viewer-logo">gzaas!</span><button className="button" onClick={edit}><Icon name="edit"/>Crear mi versión</button><button className="button" onClick={share}><Icon name="share"/>Compartir</button><button className="icon-button" aria-label="Activar pantalla completa" onClick={()=>{if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(()=>notify('Usa el modo pantalla completa de tu navegador.'));else notify('Usa el modo pantalla completa de tu navegador.');}}><Icon name="expand"/></button></div></>}
 <dialog aria-labelledby="share-title" ref={dialog} onCancel={()=>setShareOpen(false)} onClose={()=>setShareOpen(false)} onClick={e=>{if(e.target===dialog.current)setShareOpen(false);}}><div className="dialog-header"><span className="eyebrow">LISTO PARA SALIR AL MUNDO</span><button className="icon-button" aria-label="Cerrar" onClick={()=>setShareOpen(false)}><Icon name="close"/></button></div><h2 id="share-title">Que llegue a quien tú quieras<span>.</span></h2><p>Este enlace lleva tu mensaje y su diseño. Quien lo abra lo verá a toda pantalla.</p><label htmlFor="share-link">Enlace a tu mensaje</label><input id="share-link" ref={shareInput} readOnly value={shareUrl} onFocus={e=>e.target.select()}/><button className="button primary" onClick={copy}><Icon name="share"/>Copiar enlace</button>{typeof navigator.share==='function'&&<button className="button secondary" onClick={nativeShare}>Compartir con…</button>}<p className="share-note">Quien tenga el enlace puede verlo y crear su versión. Si editas el mensaje, comparte un enlace nuevo.</p>{location.protocol==='file:'&&<p className="field-error">Esta copia es local. Publica la web para compartir enlaces con otras personas.</p>}</dialog>
 <div className={'toast '+(toast?'visible':'')} role="status" aria-live="polite"><Icon name="check"/>{toast}</div>
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
